/* Seed data — dates are relative to "today" so the workspace always looks current */
const SEED_VERSION = 4;

const FORM_LIBRARY = [
  ['RPA', 'Residential Purchase Agreement', 10, 'Purchase'], ['AD', 'Disclosure Regarding Real Estate Agency', 2, 'Disclosures'],
  ['BIA', "Buyer's Inspection Advisory", 4, 'Advisories'], ['SPQ', 'Seller Property Questionnaire', 6, 'Disclosures'],
  ['TDS', 'Transfer Disclosure Statement', 4, 'Disclosures'], ['AVID', 'Agent Visual Inspection Disclosure', 2, 'Disclosures'],
  ['BRBC', 'Buyer Representation and Broker Compensation', 5, 'Purchase'], ['RR', 'Request for Repair', 2, 'Addenda'],
  ['CR-B', 'Contingency Removal', 1, 'Addenda'], ['SBSA', 'Statewide Buyer and Seller Advisory', 7, 'Advisories'],
  ['WFA', 'Wire Fraud Advisory', 1, 'Advisories'], ['RLA', 'Residential Listing Agreement', 6, 'Listing'],
  ['SCO', 'Seller Counter Offer', 2, 'Purchase'], ['BCO', 'Buyer Counter Offer', 2, 'Purchase'],
  ['SMCO', 'Seller Multiple Counter Offer', 2, 'Purchase'], ['RRRR', 'Response and Reply to Request for Repair', 2, 'Addenda'],
  ['ADM', 'Addendum', 1, 'Addenda'], ['AEA', 'Amendment of Existing Agreement Terms', 1, 'Addenda'],
  ['CC', 'Cancellation of Contract', 2, 'Purchase'], ['COP', 'Contingency for Sale of Buyer’s Property', 2, 'Addenda'],
  ['NBP', 'Notice to Buyer to Perform', 1, 'Purchase'], ['NSP', 'Notice to Seller to Perform', 1, 'Purchase'],
  ['VP', 'Verification of Property Condition', 1, 'Purchase'], ['WOO', 'Withdrawal of Offer', 1, 'Purchase'],
  ['PRBS', 'Possible Representation of More Than One Buyer or Seller', 1, 'Disclosures'], ['RCSD', 'Representative Capacity Signature Disclosure', 1, 'Disclosures'],
  ['LPD', 'Lead-Based Paint and Hazards Disclosure', 2, 'Disclosures'], ['EQ', 'Earthquake Hazards Report', 1, 'Disclosures'],
  ['ESD', 'Exempt Seller Disclosure', 2, 'Disclosures'], ['WHSD', 'Water Heater and Smoke Detector Statement', 1, 'Disclosures'],
  ['FHDA', 'Fire Hardening and Defensible Space Advisory', 3, 'Advisories'], ['MCA', 'Market Conditions Advisory', 2, 'Advisories'],
  ['BHIA', 'Buyer Homeowners’ Insurance Advisory', 1, 'Advisories'], ['DIA', 'Disclosure Information Advisory', 1, 'Advisories'],
  ['REO', 'REO Advisory', 2, 'Advisories'], ['SSA', 'Short Sale Information and Advisory', 2, 'Advisories'],
  ['HOA-IR', 'Homeowner Association Information Request', 2, 'Purchase'], ['FVAC', 'FHA/VA Amendatory Clause', 1, 'Addenda'],
  ['SIP', 'Seller In Possession Addendum', 2, 'Addenda'], ['BIP', 'Buyer In Possession Addendum', 2, 'Addenda'],
  ['TOPA', 'Tenant Occupied Property Addendum', 2, 'Addenda'], ['PAA', 'Purchase Agreement Addendum', 3, 'Addenda'],
  ['SSD', 'Short Sale Addendum', 1, 'Addenda'], ['RFR', 'Receipt for Reports', 1, 'Purchase'],
  ['MLSA', 'Modification of Terms — Listing Agreement', 1, 'Listing'], ['CL', 'Cancellation of Listing', 1, 'Listing'],
  ['SA', 'Seller’s Advisory', 3, 'Listing'], ['OHNA', 'Open House Visitor Non-Agency Disclosure', 1, 'Listing'],
  ['Counter Offer', 'Counter Offer', 2, 'Purchase'],
].map(([code, name, pages, cat]) => ({ code, name, pages, cat }));

function seedDB() {
  const now = new Date().toISOString();
  const db = {
    version: SEED_VERSION,
    session: {
      signedIn: true,
      onboarded: true,
      firstWeek: false,
      mode: 'agent',
      scope: 'org',
      sidebarCollapsed: false,
      textScale: 'standard',
    },
    user: { first: 'Chinh', last: 'Le', email: 'chinh.le@c0x12c.com', phone: '(714) 555-0142', brokerage: 'Org 1', dre: '01998877', role: 'Owner', org: 'Org 1', state: 'California', agentRole: 'Agent' },
    ui: {},
    lastTx: 't1',
    collapsed: {},
    integrations: { docusign: true, gmail: true, twilio: true, microsoft: false, google: true, drive: false },
    tx: [
      { id: 't1', title: '123 ABC Street', address: '123 ABC Street', city: 'Irvine', county: '', side: 'Buyer', clientId: 'c1', phase: 'Offer Prep', status: 'current', pinned: true, starred: true, opened: D(-14), price: 1150000, counter: 1265000, financing: 'Pre-approved to $1.3M', contingencies: 'Inspection, loan, appraisal (standard RPA)', coe: null, keyLabel: 'Offer expires', keyDate: D(0), keyTime: '17:00', keyContract: true, template: 'buyer-standard', parties: [['Maria Tran', 'Buyer'], ['Chinh Le', "Buyer's agent · DRE 01998877"], ['Lena Brooks', 'Listing agent · Coast Realty']] },
      { id: 't2', title: '9 Linden Court', address: '9 Linden Court', city: 'Newport Beach', county: 'Orange', side: 'Seller', clientId: 'c3', phase: 'Offer Prep', status: 'current', pinned: false, opened: D(-20), price: 2450000, keyLabel: 'Counter reply due', keyDate: D(1), keyTime: null, keyContract: false, template: 'seller-listing', parties: [['Okafor', 'Seller'], ['Chinh Le', "Listing agent · DRE 01998877"]] },
      { id: 't3', title: 'Alvarez family', address: '', city: 'Tustin', county: 'Orange', side: 'Buyer', clientId: 'c4', phase: 'Touring', status: 'current', opened: D(-10), keyLabel: 'Tours · 4 homes', keyDate: D(3), parties: [['Alvarez family', 'Buyer'], ['Chinh Le', "Buyer's agent"]] },
      { id: 't4', title: 'Nguyen family', address: '', city: 'Costa Mesa', county: 'Orange', side: 'Buyer', clientId: 'c6', phase: 'Prospect', status: 'current', opened: D(-6), keyLabel: 'Buyer consult', keyDate: D(2), parties: [['Nguyen family', 'Buyer'], ['Chinh Le', "Buyer's agent"]] },
      { id: 't5', title: 'Daniel Park', address: '', city: 'Lake Forest', county: 'Orange', side: 'Seller', clientId: 'c7', phase: 'Prospect', status: 'current', opened: D(-30), keyLabel: 'Last contact', keyDate: D(-9), keyPast: true, parties: [['Daniel Park', 'Seller'], ['Chinh Le', 'Listing agent']] },
      { id: 't6', title: '310 Birch Lane', address: '310 Birch Lane', city: 'Irvine', county: 'Orange', side: 'Seller', clientId: 'c5', phase: 'Closing', status: 'current', opened: D(-45), price: 1325000, coe: D(6), keyLabel: 'Closes', keyDate: D(6), signingDone: true, parties: [['Wong', 'Seller'], ['Chinh Le', 'Listing agent']] },
      { id: 't7', title: '55 Oak Avenue', address: '55 Oak Avenue', city: 'Irvine', county: 'Orange', side: 'Buyer', clientId: 'c2', phase: 'Under Contract', status: 'pending', pinned: true, opened: D(-25), price: 985000, coe: D(21), keyLabel: 'Close of escrow', keyDate: D(21), blocked: `title report pending since ${shortDate(D(-4))}`, parties: [['The Harrisons', 'Buyer'], ['Chinh Le', "Buyer's agent"], ['Priya Shah', 'Escrow · Coastline Escrow'], ['Kevin Ortiz', 'Lender · Summit Home Loans']] },
      ...[
        ['14 Willow Way', 'Irvine', 'Buyer', 'Kim family'], ['2201 Harbor Blvd #4', 'Costa Mesa', 'Seller', 'Reyes'], ['88 Canyon Ridge', 'Tustin', 'Buyer', 'Patel'],
        ['610 Seaview Dr', 'Laguna Beach', 'Seller', 'Morgan'], ['19 Orchard', 'Irvine', 'Buyer', 'Chen'], ['403 Pine St', 'Santa Ana', 'Buyer', 'Garcia'],
        ['7 Coral Tree', 'Irvine', 'Seller', 'Brooks'], ['1250 Main St #210', 'Irvine', 'Buyer', 'Singh'], ['36 Juniper', 'Lake Forest', 'Seller', 'Lopez'],
        ['5 Sandpiper', 'Newport Beach', 'Buyer', 'Nakamura'], ['912 Elm Ave', 'Fullerton', 'Seller', 'Davis'], ['77 Vista Del Mar', 'Dana Point', 'Buyer', 'Wilson'],
        ['240 Oakmont', 'Irvine', 'Buyer', 'Tran'], ['18 Laurel', 'Tustin', 'Seller', 'Hughes'], ['3301 Bayside', 'Corona del Mar', 'Buyer', 'Martin'], ['61 Meadow', 'Irvine', 'Seller', 'Ross'],
      ].map(([a, c, s, n], i) => ({ id: 'tc' + i, title: a, address: a, city: c, county: 'Orange', side: s, clientName: n, phase: 'Closed', status: 'closed', opened: D(-200 + i * 9), closed: D(-120 + i * 7), price: 800000 + i * 65000, keyLabel: 'Closed', keyDate: D(-120 + i * 7), keyPast: true, signingDone: true, parties: [[n, s], ['Chinh Le', s === 'Buyer' ? "Buyer's agent" : 'Listing agent']] })),
      ...[['501 Ocean Blvd', 'Huntington Beach', 'Buyer', 'Evans'], ['22 Cypress', 'Irvine', 'Seller', 'Ortega'], ['9 Hilltop', 'Orange', 'Buyer', 'Baker']].map(([a, c, s, n], i) => ({ id: 'ta' + i, title: a, address: a, city: c, county: 'Orange', side: s, clientName: n, phase: 'Offer Prep', status: 'archived', opened: D(-300 + i * 20), keyLabel: 'Archived', keyDate: D(-150 + i * 10), keyPast: true, parties: [[n, s]] })),
    ],
    clients: [
      { id: 'c1', name: 'Maria Tran', type: 'Buyer', stage: 'Offer Prep', priority: 'Hot', source: 'Referral', email: 'maria.tran@email.com', phone: '(949) 555-0112', area: '123 ABC Street, Irvine', lastTouch: D(0), notes: 'Prefers text over email. Wants to close before her lease ends Nov 30. Sensitive about financing — avoid CC\'ing her landlord.', timeline: [[D(-2), 'AD sent for signature'], [D(-5), 'Walked through the RPA terms on a call'], [D(-14), 'Transaction opened, RPA drafted']] },
      { id: 'c2', name: 'The Harrisons', type: 'Buyer', stage: 'Under Contract', priority: 'Warm', source: 'Past client', email: 'harrisons@email.com', phone: '(949) 555-0177', area: '55 Oak Avenue, Irvine', lastTouch: D(-3), notes: 'Second purchase with us. Anniversary of first home: Oct 14.', timeline: [[D(-3), 'Loan status call with Kevin Ortiz'], [D(-25), 'Offer accepted on 55 Oak Avenue']] },
      { id: 'c3', name: 'Okafor', type: 'Seller', stage: 'Offer Prep', priority: 'Hot', source: 'Open house', email: 'okafor.family@email.com', phone: '(949) 555-0190', area: '9 Linden Court, Newport Beach', lastTouch: D(-1), notes: 'Relocating for work in January — flexible on close date.', timeline: [[D(-1), 'Received buyer counter'], [D(-20), 'Listing signed']] },
      { id: 'c4', name: 'Alvarez family', type: 'Buyer', stage: 'Touring', priority: 'Warm', source: 'Website', email: 'alvarez.fam@email.com', phone: '(714) 555-0133', area: 'touring Tustin', lastTouch: D(0), notes: 'Need 4 bedrooms, good schools, budget up to $1.4M.', timeline: [[D(0), 'Tour route drafted for Saturday']] },
      { id: 'c5', name: 'Wong', type: 'Seller', stage: 'Closing', priority: 'Warm', source: 'Referral', email: 'wong.home@email.com', phone: '(949) 555-0161', area: '310 Birch Lane, Irvine', lastTouch: D(-3), notes: 'Moving to San Jose after close.', timeline: [[D(-3), 'Closing docs signed']] },
      { id: 'c6', name: 'Nguyen family', type: 'Buyer', stage: 'Prospect', priority: 'Warm', source: 'Website', email: 'nguyen.family@email.com', phone: '(657) 555-0149', area: 'Irvine', lastTouch: D(-5), flag: 'Check-in drafted', notes: 'First-time buyers. Interested in Woodbridge.', timeline: [[D(-5), 'Website inquiry — 4 bed near Woodbridge']] },
      { id: 'c7', name: 'Daniel Park', type: 'Seller', stage: 'Prospect', priority: 'Cold', source: 'Sign call', email: 'daniel.park@email.com', phone: '(949) 555-0108', area: 'listing consult', lastTouch: D(-9), flag: 'No contact 9d', notes: 'Thinking about listing in spring. Wants a price opinion.', timeline: [[D(-9), 'Called from yard sign']] },
    ],
    contacts: [
      ['Kevin Ortiz', 'Summit Home Loans', 'Lender', '', 'NMLS 1834920', '(714) 555-0148', 'kevin.ortiz@summithl.com', 4],
      ['Priya Shah', 'Coastline Escrow', 'Escrow', '', 'CEO-88231', '(949) 555-0117', 'priya.shah@coastlineescrow.com', 6],
      ['Lena Brooks', 'Coast Realty', 'Broker / Brokerage', 'Listing agent · Coast Realty', 'DRE 01823456', '(415) 555-0173', 'lena.brooks@coastrealty.com', 1],
      ['Marcus Webb', 'Pacific Title Co.', 'Other', 'Title officer', 'TO-40217', '(714) 555-0192', 'marcus.webb@pacifictitle.com', 3],
      ['Angela Ruiz', 'Precision Home Inspections', 'Inspector', '', 'HI-4471', '(949) 555-0136', 'angela@precisioninspect.com', 5],
      ['David Kim', 'Kim Appraisal Group', 'Appraiser', '', 'AL-33210', '(213) 555-0164', 'david.kim@kimappraisal.com', 2],
      ['Rachel Nguyen', 'Coastal Escrow Partners', 'Escrow', '', 'CEO-77104', '(657) 555-0129', 'rachel@coastalescrow.com', 2],
      ['Tom Alvarez', 'First Choice Lending', 'Lender', '', 'NMLS 992104', '(562) 555-0155', 'tom.alvarez@fcl.com', 3],
      ['Sara Patel', 'Bright Path Realty', 'Transaction coordinator', '', '—', '(310) 555-0181', 'sara.patel@brightpath.com', 1],
      ['James Liu', 'Liu & Associates Inspections', 'Inspector', '', 'HI-5502', '(626) 555-0103', 'james@liuinspections.com', 2],
      ['Monica Reyes', 'Pacific Coast Title', 'Other', 'Title officer', 'TO-51188', '(949) 555-0198', 'monica.reyes@pctitle.com', 1],
    ].map(([name, company, type, sub, license, phone, email, txCount], i) => ({ id: 'k' + i, name, company, type, sub, license, phone, email, txCount })),
    // Work items: tasks, deadlines, follow-ups. needsYou = surfaced on Home / Agenda "Needs you"
    tasks: [
      { id: 'w1', txId: 't7', title: 'Title workstream blocked', meta: `Waiting on the preliminary title report since ${shortDate(D(-4))}`, type: 'Blocked', status: 'blocked', needsYou: true, priority: 'High', due: D(0), icon: 'blocked' },
      { id: 'w2', txId: 't7', title: 'Loan contingency removal', type: 'Contract deadline', contract: true, due: D(2), status: 'todo', needsYou: true, priority: 'High', keyDate: true },
      { id: 'w3', txId: 't7', title: 'Order HOA documents', type: 'Document request', due: D(-1), status: 'todo', priority: 'Medium', owner: 'Sofia' },
      { id: 'w4', txId: 't7', title: 'Send the Harrisons a loan status update', type: 'Follow-up', due: D(-1), status: 'todo', priority: 'Medium', yours: true },
      { id: 'w5', txId: 't7', title: 'Request preliminary title report', type: 'Document request', due: D(3), status: 'blocked', priority: 'High' },
      { id: 'w6', txId: 't7', title: 'Agency disclosure missing', type: 'Compliance action', due: D(0), status: 'todo', priority: 'High', checklist: true },
      { id: 'w7', txId: 't7', title: 'Inspection contingency removal', type: 'Contingency removal', contract: true, due: D(4), status: 'todo', keyDate: true },
      { id: 'w8', txId: 't7', title: 'Close of escrow', type: 'Milestone', contract: true, due: D(21), status: 'todo', keyDate: true },
      { id: 'w10', txId: 't1', title: 'Offer expires', meta: 'RPA has 3 blanks', type: 'Contract deadline', contract: true, due: D(0), time: '17:00', status: 'todo', needsYou: true, priority: 'High', keyDate: true },
      { id: 'w11', txId: 't1', title: 'AD out for signature', meta: 'Maria Tran · sent ' + shortDate(D(-2)), type: 'Signature request', due: D(0), status: 'in-progress', needsYou: true, priority: 'High', badge: '0 of 3 signed', link: 'documents' },
      { id: 'w12', txId: 't1', title: 'Fill 3 RPA blanks', meta: 'city, county, offer expiration', type: 'Form completion', due: D(0), status: 'todo', suggested: true, priority: 'High', link: 'form' },
      { id: 'w13', txId: 't1', title: 'Call Maria about the counter', type: 'Meeting', due: D(0), time: '14:30', status: 'todo', priority: 'High' },
      { id: 'w14', txId: 't1', title: 'Review seller counter terms', type: 'To-do', due: D(0), status: 'todo', priority: 'Medium' },
      { id: 'w15', txId: 't1', title: 'Send BIA to Maria', type: 'Signature request', due: D(1), status: 'todo', priority: 'Medium' },
      { id: 'w16', txId: 't1', title: 'Acceptance', type: 'Milestone', contract: true, due: null, status: 'todo', keyDate: true },
      { id: 'w20', txId: 't2', title: 'Send SCO to the Okafors to sign', type: 'Signature request', due: D(1), status: 'todo', suggested: true, priority: 'High' },
      { id: 'w21', txId: 't3', title: 'Confirm Saturday tour route', type: 'Showing', due: D(3), status: 'todo', priority: 'Medium' },
      { id: 'w22', txId: 't4', title: 'Prep buyer consult packet', type: 'To-do', due: D(2), status: 'todo', priority: 'Medium' },
      { id: 'w23', txId: 't5', title: 'Check in about listing timeline', type: 'Follow-up', due: D(-9), status: 'todo', priority: 'Medium', clientId: 'c7' },
      { id: 'w24', txId: 't6', title: 'Final walkthrough', type: 'Event', due: D(5), status: 'todo', priority: 'Medium' },
      { id: 'w25', txId: null, clientId: 'c7', title: 'Daniel Park — check in', meta: `Follow-up · seller prospect · no contact since ${shortDate(D(-9))}`, type: 'Follow-up', due: D(-9), status: 'todo', needsYou: true, people: true, priority: 'Medium' },
    ],
    events: [
      { id: 'e1', title: 'Morning prospecting', type: 'Time block', date: D(0), start: '08:00', end: '09:00', txId: null },
      { id: 'e2', title: 'Home inspection', type: 'Inspection', date: D(0), start: '10:00', end: '11:00', txId: 't7', people: ['the Harrisons'], location: '55 Oak Avenue, Irvine, CA', remind: ['1 hour before'] },
      { id: 'e3', title: 'Call with Maria Tran', type: 'Meeting', date: D(0), start: '14:30', end: '15:15', txId: 't1', people: ['Maria Tran'] },
      { id: 'e4', title: 'Offer expires', type: 'Contract deadline', date: D(0), start: '17:00', end: '17:00', txId: 't1', contract: true, allDay: false },
      { id: 'e5', title: 'Reply to Okafor counter', type: 'Time block', date: D(1), start: '09:30', end: '10:30', txId: 't2' },
      { id: 'e6', title: 'Prospecting block', type: 'Time block', date: D(2), start: '08:00', end: '09:30' },
      { id: 'e7', title: 'Appraiser visit', type: 'Appraisal', date: D(5), start: '10:00', end: '11:00', txId: 't7' },
      { id: 'e8', title: 'Alvarez tours', type: 'Showing', date: D(3), allDay: true, txId: 't3' },
      { id: 'e9', title: 'Nguyen consult', type: 'Meeting', date: D(2), allDay: true, txId: 't4' },
      { id: 'e10', title: 'Final walkthrough', type: 'Walkthrough', date: D(5), start: '16:00', end: '17:00', txId: 't6' },
    ],
    suggestions: {
      source: 'Counter from Lena Brooks (listing agent) · email, 9:12 AM',
      items: [
        { id: 's1', title: 'Final walkthrough', meta: `Event · ${wdDate(D(20))} · 4 PM`, kind: 'event', checked: true, payload: { title: 'Final walkthrough', type: 'Walkthrough', date: D(20), start: '16:00', end: '17:00', txId: 't1' } },
        { id: 's2', title: 'Tell Maria the counter terms', meta: 'Follow-up · Maria Tran · today', kind: 'task', checked: true, payload: { title: 'Tell Maria the counter terms', type: 'Follow-up', due: D(0), txId: 't1', clientId: 'c1' } },
        { id: 's3', title: `Move offer expiration to ${WD[pd(D(1)).getDay()]} 5 PM`, meta: 'needs your confirmation', contract: true, kind: 'contract', checked: true, payload: { txId: 't1', date: D(1), time: '17:00' } },
      ],
    },
    followUps: [
      { id: 'f1', clientId: 'c7', name: 'Daniel Park', title: 'Check in about listing timeline', type: 'Follow-up', due: D(-9), draft: { channel: 'Text', text: 'Hi Daniel, checking in on your listing timeline. Happy to walk through a quick price opinion whenever works this week.' } },
      { id: 'f2', clientId: 'c1', name: 'Maria Tran', title: 'Call about the counter offer', type: 'Meeting', due: D(0), time: '14:30', txId: 't1' },
      { id: 'f3', clientId: 'c6', name: 'Nguyen family', title: 'Send 3 new Irvine listings', type: 'Follow-up', due: D(0), draft: { channel: 'Email', text: 'Three new Irvine listings that match your list, including a 4-bed near Woodbridge. Want to see any of them this weekend?' } },
      { id: 'f4', clientId: 'c4', name: 'Alvarez family', title: 'Tour recap + next showings', type: 'Follow-up', due: D(2) },
      { id: 'f5', clientId: null, name: 'Priya Shah', tag: 'Past client', title: 'Send CMA for her condo', type: 'To-do', due: D(4) },
      { id: 'f6', clientId: 'c2', name: 'The Harrisons', title: 'Home anniversary call', type: 'Call', due: D(21), repeats: 'yearly' },
      ...Array.from({ length: 18 }, (_, i) => ({ id: 'fd' + i, clientId: null, name: ['Kim family', 'Reyes', 'Patel', 'Morgan', 'Chen', 'Garcia'][i % 6], title: ['Closing gift delivered', 'Sent market update', 'Thank-you call', 'Shared school report'][i % 4], type: 'Follow-up', due: D(-3 - i * 2), done: true })),
    ],
    checklist: [
      { id: 'k1', txId: 't1', level: 'transaction', title: 'Agency Disclosure', code: 'AD', due: D(0), time: '17:00', owner: 'Chinh Le', link: 'Signature request', done: false, note: 'Out for signature · 0 of 3 signed' },
      { id: 'k2', txId: 't1', level: 'transaction', title: 'Buyer Representation Agreement', code: 'BRBC', due: D(-11), owner: 'Chinh Le', link: 'Signature request', done: true, auto: 'when signed via DocuSign' },
      { id: 'k3', txId: 't1', level: 'transaction', title: 'Wire Fraud Advisory', code: 'WFA', due: D(-11), owner: 'Chinh Le', link: 'Signature request', done: true, auto: 'when signed via DocuSign' },
      { id: 'k4', txId: 't1', level: 'transaction', title: 'Proof of funds / Pre-approval', code: '', due: D(-1), owner: 'Maria Tran', link: 'Document request', done: true, auto: 'when received via Communication log' },
      { id: 'k10', txId: 't7', level: 'transaction', title: 'Agency Disclosure', code: 'AD', due: D(0), owner: 'Chinh Le', link: 'Signature request', done: false },
      { id: 'k11', txId: 't7', level: 'transaction', title: 'Residential Purchase Agreement', code: 'RPA', due: D(-25), owner: 'Chinh Le', link: 'Signature request', done: true },
      { id: 'k12', txId: 't7', level: 'transaction', title: 'Transfer Disclosure Statement', code: 'TDS', due: D(-18), owner: 'Chinh Le', link: 'Document request', done: true },
      { id: 'k13', txId: 't7', level: 'transaction', title: 'Buyer Inspection Advisory', code: 'BIA', due: D(-20), owner: 'Chinh Le', link: 'Signature request', done: true },
      { id: 'k20', txId: 't2', level: 'transaction', title: 'Residential Listing Agreement', code: 'RLA', due: D(-20), owner: 'Chinh Le', link: 'Signature request', done: true },
      { id: 'k21', txId: 't2', level: 'transaction', title: 'Seller Property Questionnaire', code: 'SPQ', due: D(3), owner: 'Okafor', link: 'Signature request', done: false },
      { id: 'k22', txId: 't2', level: 'transaction', title: 'Transfer Disclosure Statement', code: 'TDS', due: D(3), owner: 'Okafor', link: 'Signature request', done: false },
      { id: 'k30', txId: 't3', level: 'transaction', title: 'Buyer Representation Agreement', code: 'BRBC', due: D(-10), owner: 'Chinh Le', link: 'Signature request', done: true },
      { id: 'k31', txId: 't3', level: 'transaction', title: 'Pre-approval letter', code: '', due: D(-8), owner: 'Alvarez family', link: 'Document request', done: true },
      ...Array.from({ length: 9 }, (_, i) => ({ id: 'k6' + i, txId: 't6', level: 'transaction', title: ['Listing agreement', 'SPQ', 'TDS', 'AVID', 'RPA', 'Counter', 'Repairs', 'Contingency removal', 'Closing docs'][i], code: '', due: D(-40 + i * 4), owner: 'Chinh Le', link: 'Signature request', done: true })),
    ],
    docs: [
      { id: 'd1', txId: 't1', code: 'RPA', name: 'Residential Purchase Agreement', status: 'draft', progress: 62, pages: 10, updated: D(0), updatedTime: '9:15 AM', source: 'Form' },
      { id: 'd2', txId: 't1', code: 'AD', name: 'Agency Disclosure', status: 'out', signed: 0, signers: 3, pages: 2, updated: D(-1), source: 'Envelope' },
      { id: 'd3', txId: 't1', code: 'BIA', name: "Buyer's Inspection Advisory", status: 'not-started', progress: 0, pages: 4, updated: D(-14), source: 'Form' },
      { id: 'd4', txId: 't1', code: '', name: 'Pre-approval letter', status: 'filed', pages: 1, updated: D(-1), source: 'Call', filedBy: 'Sofia', from: 'Kevin Ortiz · call' },
      { id: 'd5', txId: 't1', code: '', name: 'Escrow instructions draft.pdf', status: 'filed', pages: 4, updated: D(-1), updatedTime: '11:20 AM', source: 'Email', filedBy: 'Sofia', from: 'From Priya Shah · email' },
      { id: 'd10', txId: 't7', code: 'RPA', name: 'Residential Purchase Agreement', status: 'signed', pages: 10, updated: D(-25), source: 'Envelope' },
      { id: 'd11', txId: 't7', code: 'TDS', name: 'Transfer Disclosure Statement', status: 'signed', pages: 4, updated: D(-18), source: 'Envelope' },
      { id: 'd12', txId: 't7', code: 'AD', name: 'Agency Disclosure', status: 'draft', progress: 40, pages: 2, updated: D(-2), source: 'Form' },
      { id: 'd20', txId: 't2', code: 'SCO', name: 'Seller Counter Offer', status: 'draft', progress: 80, pages: 2, updated: D(-1), source: 'Form' },
      { id: 'd21', txId: 't2', code: 'RLA', name: 'Residential Listing Agreement', status: 'signed', pages: 6, updated: D(-20), source: 'Envelope' },
    ],
    envelopes: [
      { id: 'v1', txId: 't1', code: 'AD', name: 'Agency Disclosure', sent: D(-2), by: 'Chinh Le', status: 'out', recipients: [{ name: 'Maria Tran', role: 'Buyer', status: 'Delivered', note: `Opened ${shortDate(D(-1))}, 9:04 PM · not signed` }, { name: 'Lena Brooks', role: 'Listing agent, Coast Realty', status: 'Waiting', note: 'Receives it after Maria signs' }, { name: 'Chinh Le', role: "Buyer's agent", status: 'Waiting', note: 'Signs last' }] },
    ],
    messages: [
      { id: 'm1', txId: 't1', day: D(-2), time: '10:02 AM', from: 'Lena Brooks', role: 'Listing agent · Coast Realty', channel: 'Email', subject: 'Seller disclosures (TDS) coming Friday', body: '' },
      { id: 'm2', txId: 't1', day: D(-1), time: '11:20 AM', from: 'Priya Shah', role: 'Escrow', channel: 'Email', subject: 'Escrow instructions draft', body: '' },
      { id: 'm3', txId: 't1', day: D(0), time: '8:40 AM', from: 'Maria Tran', role: 'Buyer', channel: 'SMS', body: 'Can we talk after lunch about the counter?' },
    ],
    activity: [
      { id: 'a1', txId: 't1', text: 'AD sent for signature to Maria Tran, Lena Brooks, Chinh Le', kind: 'signing', at: new Date(Date.now() - 2 * DAY).toISOString() },
      { id: 'a2', txId: 't1', text: 'RPA page 1 filled by Sofia (buyer, address, price)', kind: 'form', at: new Date(Date.now() - 2 * DAY - 3600e3).toISOString() },
      { id: 'a3', txId: 't1', text: 'Transaction opened from template “Buyer — standard purchase”', kind: 'create', at: new Date(Date.now() - 14 * DAY).toISOString() },
    ],
    templates: [
      { id: 'buyer-standard', name: 'Buyer — standard purchase', side: 'Buyer', forms: ['RPA', 'AD', 'BIA', 'SBSA', 'WFA', 'BRBC'] },
      { id: 'seller-listing', name: 'Seller — listing', side: 'Seller', forms: ['RLA', 'AD', 'SPQ', 'TDS', 'AVID', 'WFA'] },
      { id: 'counter-offer', name: 'Counter offer', side: 'Situational', forms: ['Counter Offer'] },
      { id: 'contingency-removal', name: 'Contingency removal', side: 'Situational', forms: ['CR-B'] },
    ],
    chats: [
      { id: 'ch1', title: '123 ABC Street — offer prep', txId: 't1', designed: true, updated: now, messages: [] },
      { id: 'ch2', title: 'Follow-ups this week', txId: null, updated: now, messages: [
        { role: 'user', text: 'Who should I follow up with this week?' },
        { role: 'sofia', text: 'Six follow-ups are due this week. Daniel Park is overdue (no contact in 9 days) and I drafted a text for him. Maria Tran has a call today at 2:30 PM, and the Nguyen family are waiting on 3 new Irvine listings — that email is drafted too.', actions: [['Open follow-ups', '#/follow-ups']] },
      ] },
      { id: 'ch3', title: '55 Oak Avenue compliance check', txId: 't7', updated: now, messages: [
        { role: 'user', text: "What's missing for compliance on 55 Oak Avenue?" },
        { role: 'sofia', text: 'One required item is open: the Agency Disclosure (AD) was never signed. Everything else — RPA, TDS, BIA — is signed and filed. The title workstream is also blocked on the preliminary title report.', actions: [['Open checklist', '#/tx/t7/checklist']] },
      ] },
    ],
    notifications: [
      { id: 'n1', title: 'AD viewed by Maria Tran', body: '123 ABC Street · DocuSign', link: '#/tx/t1/documents', at: now, read: false },
      { id: 'n2', title: 'Counter offer received', body: 'Lena Brooks · $1,265,000 on 123 ABC Street', link: '#/tx/t1/log', at: now, read: false },
      { id: 'n3', title: 'Loan contingency removal due Friday', body: '55 Oak Avenue · contract deadline', link: '#/tx/t7', at: now, read: true },
    ],
    routines: {},
  };
  return db;
}
